clouds:
  sku-101:
    auth:
      auth_url: http://192.168.122.213:5000/v3
      username: broskos
      password: redhat
      project_name: admin
      user_domain_name: default
      project_domain_name: default
    identity_api_version: 3
  sku-201:
    auth:
      auth_url: http://192.168.122.32:5000/v3
      username: broskos
      password: redhat
      project_name: admin
      user_domain_name: default
      project_domain_name: default
    identity_api_version: 3
  sku-301:
    auth:
      auth_url: http://192.168.122.156:5000/v3
      username: broskos
      password: redhat
      project_name: admin
      user_domain_name: default
      project_domain_name: default
    identity_api_version: 3