---
- name: Ensure OpenStack projects are registered
  hosts: localhost
  roles:
    - role: stackhpc.os-projects
      os_projects_venv: "~/os-projects-venv"
      os_projects_auth_type: "password"
      os_projects_auth:
        project_name: admin
        username: admin
        password: 67rKWRH9rJmwRxAaTP37F3FD2
        auth_url: http://192.168.100.58:5000/v2.0
      os_projects:
        - name: project1
          description: An example project
          project_domain: default
          user_domain: default
