- hosts: datacenters
  gather_facts: no
  environment:
    OS_IDENTITY_API_VERSION: 3
  tasks:
  - debug:
      msg: "{{ auth_info }}"

  - os_project:
      auth: "{{ auth_info }}"
      state: present
      name: "{{ item.value.project_name }}"
      description: "{{ item.value.project_description }} Datacenter: {{ datacenter_name }} sku: {{ sku_name }}"
      domain_id: default
      enabled: True
    delegate_to: localhost
    with_dict: "{{ vnf }}"

  - os_group:
      auth: "{{ auth_info }}"
      state: present
      name: "{{ item.value.member_group }}"
      description: "member group for project {{ item.value.project_name }}"
    delegate_to: localhost
    with_dict: "{{ vnf }}"

  - os_user_role:
      auth: "{{ auth_info }}"
      group: "{{ item.value.member_group }}"
      project: "{{ item.value.project_name }}"
      role: _member_
    delegate_to: localhost
    with_dict: "{{ vnf }}"

  - include: create_network.yml
    delegate_to: localhost
    with_dict: "{{ vnf }}"
    loop_control:
      loop_var: vnf_info

  - include: create_subnet.yml
    delegate_to: localhost
    with_dict: "{{ vnf }}"
    loop_control:
      loop_var: vnf_info