- hosts: localhost
  gather_facts: no
  tasks:

  - name: template clouds.yml
    template:
      src: clouds.j2
      dest: ./clouds.yml
    delegate_to: localhost

  - debug:
      var: hostvars[inventory_hostname]


- hosts: datacenters
  gather_facts: no
  environment:
  tasks:

  - os_project:
      cloud: "{{ sku_name }}"
      state: present
      name: "{{ item.value.project_name }}"
      description: "{{ item.value.project_description }} Datacenter: {{ datacenter_name }} sku: {{ sku_name }}"
      domain_id: default
      enabled: True
    delegate_to: localhost
    with_dict: "{{ vnf }}"

  - os_group:
      cloud: "{{ sku_name }}"
      state: present
      name: "{{ item.value.member_group }}"
      description: "member group for project {{ item.value.project_name }}"
    delegate_to: localhost
    with_dict: "{{ vnf }}"

  - os_user_role:
      cloud: "{{ sku_name }}"
      group: "{{ item.value.member_group }}"
      project: "{{ item.value.project_name }}"
      role: _member_
    delegate_to: localhost
    with_dict: "{{ vnf }}"

  - include: create_network.yml
    delegate_to: localhost
    with_dict: "{{ vnf }}"
    loop_control:
      loop_var: vnf_info

  - include: create_subnet.yml
    delegate_to: localhost
    with_dict: "{{ vnf }}"
    loop_control:
      loop_var: vnf_info